# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2436da9260d5e2fcd3fe51895135074ed0f721bd987bee40b1f75e18455cdb99949203fe930dfa55c541273e87f5db79bea5d0a6cf3f9fa4cbf775bafd535968

test:
  secret_key_base: f656ec54b147daf7952ceca963a56feb35bbfff31ca2cf9bbdc5ec1064d91fcf4d6a1bd4147383978e5777cae8cd2e3c9a3459561bc4157ce24a4f5bec26259c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
